apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ecommerce
  namespace: argocd
spec:
  description: E-Commerce Microservices Platform
  sourceRepos:
    - 'https://github.com/yesk993-ops/ecommerce-manifests.git'
  destinations:
    - namespace: ecommerce
      server: https://kubernetes.default.svc
    - namespace: ecommerce-infra
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
