apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  NODE_ENV: production
  DB_HOST: postgres.ecommerce-infra.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: ecommerce
  REDIS_HOST: redis.ecommerce-infra.svc.cluster.local
  REDIS_PORT: "6379"
  KAFKA_BROKERS: kafka.ecommerce-infra.svc.cluster.local:9092
  AUTH_SERVICE_URL: http://auth-service.ecommerce.svc.cluster.local:4001
  USER_SERVICE_URL: http://user-service.ecommerce.svc.cluster.local:4002
  PRODUCT_SERVICE_URL: http://product-service.ecommerce.svc.cluster.local:4003
  CART_SERVICE_URL: http://cart-service.ecommerce.svc.cluster.local:4004
  ORDER_SERVICE_URL: http://order-service.ecommerce.svc.cluster.local:4005
  PAYMENT_SERVICE_URL: http://payment-service.ecommerce.svc.cluster.local:4006
  INVENTORY_SERVICE_URL: http://inventory-service.ecommerce.svc.cluster.local:4007
  NOTIFICATION_SERVICE_URL: http://notification-service.ecommerce.svc.cluster.local:4008
  SMTP_HOST: mailhog.ecommerce-infra.svc.cluster.local
  SMTP_PORT: "1025"
  LOG_LEVEL: info
  PROMETHEUS_SCRAPE: "true"
