apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
data:
  DB_USER: ZWNvbW1lcmNl
  DB_PASSWORD: ZWNvbW1lcmNlX3Bhc3M=
  REDIS_PASSWORD: cmVkaXNfcGFzcw==
  JWT_SECRET: ZGV2LWp3dC1zZWNyZXQtY2hhbmdlLWluLXByb2R1Y3Rpb24=
  JWT_REFRESH_SECRET: ZGV2LXJlZnJlc2gtc2VjcmV0LWNoYW5nZS1pbi1wcm9kdWN0aW9u
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: ecommerce-infra
type: Opaque
data:
  postgres-password: ZWNvbW1lcmNlX3Bhc3M=
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: ecommerce-infra
type: Opaque
data:
  redis-password: cmVkaXNfcGFzcw==
