apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: production
  managed-by: argocd
resources:
  - ../../base/auth
  - ../../base/user
  - ../../base/product
  - ../../base/cart
  - ../../base/order
  - ../../base/payment
  - ../../base/inventory
  - ../../base/notification
  - ../../base/gateway
  - ../../base/frontend
images:
  - name: placeholder/auth-service
    newName: mydocker3692/ecommerce-app
    newTag: auth-service-17-a70b8c2
  - name: placeholder/user-service
    newName: mydocker3692/ecommerce-app
    newTag: user-service-17-a70b8c2
  - name: placeholder/product-service
    newName: mydocker3692/ecommerce-app
    newTag: product-service-17-a70b8c2
  - name: placeholder/cart-service
    newName: mydocker3692/ecommerce-app
    newTag: cart-service-17-a70b8c2
  - name: placeholder/order-service
    newName: mydocker3692/ecommerce-app
    newTag: order-service-17-a70b8c2
  - name: placeholder/payment-service
    newName: mydocker3692/ecommerce-app
    newTag: payment-service-17-a70b8c2
  - name: placeholder/inventory-service
    newName: mydocker3692/ecommerce-app
    newTag: inventory-service-17-a70b8c2
  - name: placeholder/notification-service
    newName: mydocker3692/ecommerce-app
    newTag: notification-service-17-a70b8c2
  - name: placeholder/api-gateway
    newName: mydocker3692/ecommerce-app
    newTag: api-gateway-17-a70b8c2
  - name: placeholder/frontend
    newName: mydocker3692/ecommerce-app
    newTag: frontend-18-5668f6c
