apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ecommerce
commonLabels:
  environment: production
  managed-by: argocd
resources:
  - ../../base/auth
  - ../../base/user
  - ../../base/product
  - ../../base/cart
  - ../../base/order
  - ../../base/payment
  - ../../base/inventory
  - ../../base/notification
  - ../../base/gateway
  - ../../base/frontend
  - ../../base/infra/namespace.yaml
  - ../../base/infra/configmap.yaml
  - ../../base/infra/secrets.yaml
  - ../../base/infra/ingress.yaml
  - ../../base/infra/rbac.yaml
images:
  - name: placeholder/auth-service
    newName: mydocker3692/ecommerce-app
    newTag: auth-service-latest
  - name: placeholder/user-service
    newName: mydocker3692/ecommerce-app
    newTag: user-service-latest
  - name: placeholder/product-service
    newName: mydocker3692/ecommerce-app
    newTag: product-service-latest
  - name: placeholder/cart-service
    newName: mydocker3692/ecommerce-app
    newTag: cart-service-latest
  - name: placeholder/order-service
    newName: mydocker3692/ecommerce-app
    newTag: order-service-latest
  - name: placeholder/payment-service
    newName: mydocker3692/ecommerce-app
    newTag: payment-service-latest
  - name: placeholder/inventory-service
    newName: mydocker3692/ecommerce-app
    newTag: inventory-service-latest
  - name: placeholder/notification-service
    newName: mydocker3692/ecommerce-app
    newTag: notification-service-latest
  - name: placeholder/api-gateway
    newName: mydocker3692/ecommerce-app
    newTag: api-gateway-latest
  - name: placeholder/frontend
    newName: mydocker3692/ecommerce-app
    newTag: frontend-latest
